version: '3.8'

services:
    gen:
        container_name: gen
        build:
            context: ../rabbitmq-docs/generator
            dockerfile: Dockerfile
        environment:
            APP_DEBUG: "false"
            TO_USERNAME: "rmuser"
            TO_PASSWORD: "rmpassword"
            TO_HOSTNAME: "rabbitmq"
            TO_PORT: "5672"
            TO_QUEUE: "inbox"
            TO_EXCHANGE: "in"
            TO_ROUTINGKEY: "gen"
            TO_PASSIVE: "false"
            MCH_MODE: "false"
            JOB_MODE: "false"
            COUNT: "1000000"
            SLEEP: "100"
        restart: always

    consumer:
        container_name: consumer
        build:
            context: ../rabbitmq-docs/consumer
            dockerfile: Dockerfile
        restart: always
        environment:
            FAIL: "true"
            SLEEP: "250"
            FROM_USERNAME: "rmuser"
            FROM_PASSWORD: "rmpassword"
            FROM_HOSTNAME: "rabbitmq"
            FROM_PORT: "5672"
            FROM_QUEUE: "inbox"
            FROM_EXCHANGE: "in"
            FROM_ROUTINGKEY: "gen"
            FROM_PASSIVE: "false"
            RETRY_QUEUE: "false"
            RETRY_QUEUE_TTL: "15000"
            PREFETCH: "2"

    rabbitmq:
        image: rabbitmq:3.13.1-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
        volumes:
            -   ./rabbitmq:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"

volumes:
    rabbitmq: