version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3.13.1-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        volumes:
            -   ./rabbitmq:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"

volumes:
    rabbitmq: